name: Create SuperSnyk 次 Pull Request
on:
  # workflow_dispatch:
  push

jobs:
  create-supersnyk-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
          fetch-depth: 0
      - uses: bobvanderlinden/combine-pull-requests@v3
        with:
          label: snyk
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Get Snyk PRs metadata
        run: ./.github/get-snyk-prs-metadata.sh
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create SuperSnyk 次 PR
        uses: peter-evans/create-pull-request@v4
        with:
          title: 次 SuperSnyk
          body: "次 SuperSnyk PR created with [create-pull-request](https://github.com/peter-evans/create-pull-request)\n${{ env.SUPERSNYK_PR_BODY }}"
          author: 次 SuperSnyk-bot <${{ github.actor }}@users.noreply.github.com>
